package ffconstant

const LIBAVFILTER_VERSION_MAJOR = 7
const LIBAVFILTER_VERSION_MINOR = 110
const LIBAVFILTER_VERSION_MICRO = 100

//const LIBAVFILTER_VERSION_INT = 1 //AV_VERSION_INT(LIBAVFILTER_VERSION_MAJOR, \
//LIBAVFILTER_VERSION_MINOR, \
//LIBAVFILTER_VERSION_MICRO)
//const LIBAVFILTER_VERSION = 1 //  AV_VERSION(LIBAVFILTER_VERSION_MAJOR,   \
//LIBAVFILTER_VERSION_MINOR,   \
//LIBAVFILTER_VERSION_MICRO)
//const LIBAVFILTER_BUILD = LIBAVFILTER_VERSION_INT

const LIBAVFILTER_IDENT = "" //    "Lavfi" AV_STRINGIFY(LIBAVFILTER_VERSION)

/**
 * FF_API_* defines may be placed below to indicate public API that will be
 * dropped at a future version bump. The defines themselves are not part of
 * the public API and may change, break or disappear at any time.
 */

const FF_API_OLD_FILTER_OPTS_ERROR = (LIBAVFILTER_VERSION_MAJOR < 8)
const FF_API_LAVR_OPTS = (LIBAVFILTER_VERSION_MAJOR < 8)
const FF_API_FILTER_GET_SET = (LIBAVFILTER_VERSION_MAJOR < 8)
const FF_API_SWS_PARAM_OPTION = (LIBAVFILTER_VERSION_MAJOR < 8)

//const FF_API_NEXT = (LIBAVFILTER_VERSION_MAJOR < 8)
const FF_API_FILTER_LINK_SET_CLOSED = (LIBAVFILTER_VERSION_MAJOR < 8)
const FF_API_BUFFERSINK_ALLOC = (LIBAVFILTER_VERSION_MAJOR < 9)
