package ffconstant

// Major bumping may affect Ticket5467, 5421, 5451(compatibility with Chromium)
// Also please add any ticket numbers that you believe might be affected here
const LIBAVFORMAT_VERSION_MAJOR = 58
const LIBAVFORMAT_VERSION_MINOR = 76
const LIBAVFORMAT_VERSION_MICRO = 100

const LIBAVFORMAT_VERSION_INT = 1 //AV_VERSION_INT(LIBAVFORMAT_VERSION_MAJOR, \
//LIBAVFORMAT_VERSION_MINOR, \
//LIBAVFORMAT_VERSION_MICRO)
const LIBAVFORMAT_VERSION = 1 // AV_VERSION(LIBAVFORMAT_VERSION_MAJOR,   \
//LIBAVFORMAT_VERSION_MINOR,   \
//LIBAVFORMAT_VERSION_MICRO)
const LIBAVFORMAT_BUILD = LIBAVFORMAT_VERSION_INT

const LIBAVFORMAT_IDENT = "" //   "Lavf" AV_STRINGIFY(LIBAVFORMAT_VERSION)

/**
 * FF_API_* defines may be placed below to indicate public API that will be
 * dropped at a future version bump. The defines themselves are not part of
 * the public API and may change, break or disappear at any time.
 *
 * @note, when bumping the major version it is recommended to manually
 * disable each FF_API_* in its own commit instead of disabling them all
 * at once through the bump. This improves the git bisect-ability of the change.
 *
 */
const FF_API_COMPUTE_PKT_FIELDS2 = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_OLD_OPEN_CALLBACKS = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_LAVF_AVCTX = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_HTTP_USER_AGENT = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_HLS_WRAP = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_HLS_USE_LOCALTIME = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_LAVF_KEEPSIDE_FLAG = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_OLD_ROTATE_API = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_FORMAT_GET_SET = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_OLD_AVIO_EOF_0 = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_LAVF_FFSERVER = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_FORMAT_FILENAME = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_OLD_RTSP_OPTIONS = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_NEXT = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_DASH_MIN_SEG_DURATION = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_LAVF_MP4A_LATM = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_AVIOFORMAT = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_DEMUXER_OPEN = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_CHAPTER_ID_INT = (LIBAVFORMAT_VERSION_MAJOR < 59)
const FF_API_LAVF_PRIV_OPT = (LIBAVFORMAT_VERSION_MAJOR < 60)

const FF_API_R_FRAME_RATE = 1
