package ffconstant

const LIBPOSTPROC_VERSION_MAJOR = 55
const LIBPOSTPROC_VERSION_MINOR = 9
const LIBPOSTPROC_VERSION_MICRO = 100

const LIBPOSTPROC_VERSION_INT = 1 //AV_VERSION_INT(LIBPOSTPROC_VERSION_MAJOR, \
//LIBPOSTPROC_VERSION_MINOR, \
//LIBPOSTPROC_VERSION_MICRO)
const LIBPOSTPROC_VERSION = 1 //AV_VERSION(LIBPOSTPROC_VERSION_MAJOR, \
//LIBPOSTPROC_VERSION_MINOR, \
//LIBPOSTPROC_VERSION_MICRO)
const LIBPOSTPROC_BUILD = LIBPOSTPROC_VERSION_INT

const LIBPOSTPROC_IDENT = "" // "postproc" AV_STRINGIFY(LIBPOSTPROC_VERSION)
