package ffconstant

const LIBSWRESAMPLE_VERSION_MAJOR = 3
const LIBSWRESAMPLE_VERSION_MINOR = 9
const LIBSWRESAMPLE_VERSION_MICRO = 100

const LIBSWRESAMPLE_VERSION_INT = 1 //AV_VERSION_INT(LIBSWRESAMPLE_VERSION_MAJOR, \
//LIBSWRESAMPLE_VERSION_MINOR, \
//LIBSWRESAMPLE_VERSION_MICRO)
const LIBSWRESAMPLE_VERSION = 1 //AV_VERSION(LIBSWRESAMPLE_VERSION_MAJOR, \
//LIBSWRESAMPLE_VERSION_MINOR, \
//LIBSWRESAMPLE_VERSION_MICRO)
const LIBSWRESAMPLE_BUILD = LIBSWRESAMPLE_VERSION_INT

const LIBSWRESAMPLE_IDENT = "" // "SwR" AV_STRINGIFY(LIBSWRESAMPLE_VERSION)
