package ffconstant

const LIBSWSCALE_VERSION_MAJOR = 5
const LIBSWSCALE_VERSION_MINOR = 9
const LIBSWSCALE_VERSION_MICRO = 100

//const LIBSWSCALE_VERSION_INT = 1 // AV_VERSION_INT(LIBSWSCALE_VERSION_MAJOR, \
//LIBSWSCALE_VERSION_MINOR, \
//LIBSWSCALE_VERSION_MICRO)
//const LIBSWSCALE_VERSION = 1 // AV_VERSION(LIBSWSCALE_VERSION_MAJOR, \
//LIBSWSCALE_VERSION_MINOR, \
//LIBSWSCALE_VERSION_MICRO)
//const LIBSWSCALE_BUILD = LIBSWSCALE_VERSION_INT
const LIBSWSCALE_IDENT = "" // "SwS" AV_STRINGIFY(LIBSWSCALE_VERSION)
const FF_API_SWS_VECTOR = (LIBSWSCALE_VERSION_MAJOR < 6)
