package libavutil

/* Generated by ffmpeg configure */
//#ifndef AVUTIL_AVCONFIG_H
//const AVUTIL_AVCONFIG_H
const AV_HAVE_BIGENDIAN = 0
const AV_HAVE_FAST_UNALIGNED = 1

//#endif /* AVUTIL_AVCONFIG_H */
